name: test
on:
  push
  4 | jobs:
    5 |   test:
      >  6 |     needs: build
      |     ^^^^^^^^^^^^
      >  7 |     runs-on: ubuntu-22.04
      | ^^^^^^^^^^^^^^^^^^^^^^^^^
      >  8 |     steps:
        | ^^^^^^^^^^^^^^^^^^^^^^^^^
        >  9 |       - name: check out code
        | ^^^^^^^^^^^^^^^^^^^^^^^^^
        > 10 |         uses: actions/checkout@v3
        | ^^^^^^^^^^^^^^^^^^^^^^^^^
        > 11 |       - name: validate html and print params"
        | ^^^^^^^^^^^^^^^^^^^^^^^^^
        > 12 |         run: |
          | ^^^^^^^^^^^^^^^^^^^^^^^^^
          > 13 |           echo "running test and validation build"
          | ^^^^^^^^^^^^^^^^^^^^^^^^^
          > 14 |            echo "Environment  : %env.name%"
          | ^^^^^^^^^^^^^^^^^^^^^^^^^
          > 15 |            echo "Version      : %system.version%"
          | ^^^^^^^^^^^^^^^^^^^^^^^^^
          > 16 |            echo "App Env      : ${'$'}APP_ENV"
          | ^^^^^^^^^^^^^^^^^^^^^^^^^
          > 17 |        - name: checking html files
          | ^^^^^^^^^^^^^^^^^^^^^^^^^
          > 18 |         run: |
            | ^^^^^^^^^^^^^^^^^^^^^^^^^
            > 19 |          if [ -f index.html ]; then
            | ^^^^^^^^^^^^^^^^^^^^^^^^^
            > 20 |                   echo "index.html found!"
            | ^^^^^^^^^^^^^^^^^^^^^^^^^
            > 21 |                 else
            | ^^^^^^^^^^^^^^^^^^^^^^^^^
            > 22 |                   echo "index.html MISSING - Build Failed!"
            | ^^^^^^^^^^^^^^^^^^^^^^^^^
            > 23 |                   exit 1
            | ^^^^^^^^^^^^^^^^^^^^^^^^^
            > 24 |                 fi
            | ^^^^^^^^^^^^^^^^^^^^^^^^^
            > 25 |         - name: checking html tags
            | ^^^^^^^^^^^^^^^^^^^^^^^^^
            > 26 |           run: |
              | ^^^^^^^^^^^^^^^^^^^^^^^^^
              > 27 |             if grep -q "<html" index.html; then
              | ^^^^^^^^^^^^^^^^^^^^^^^^^
              > 28 |                   echo "<html> tag found!"
              | ^^^^^^^^^^^^^^^^^^^^^^^^^
              > 29 |                 else
              | ^^^^^^^^^^^^^^^^^^^^^^^^^
              > 30 |                   echo "Missing <html> tag!"
              | ^^^^^^^^^^^^^^^^^^^^^^^^^
              > 31 |                   exit 1
              | ^^^^^^^^^^^^^^^^^^^^^^^^^
              > 32 |                 fi
              | ^^^^^^^^^^^^^^^^^^^^^^^^^
              > 33 |                 if grep -q "<body" index.html; then
              | ^^^^^^^^^^^^^^^^^^^^^^^^^
              > 34 |                   echo "<body> tag found!"
              | ^^^^^^^^^^^^^^^^^^^^^^^^^
              > 35 |                 else
              | ^^^^^^^^^^^^^^^^^^^^^^^^^
              > 36 |                   echo "Missing <body> tag!"
              | ^^^^^^^^^^^^^^^^^^^^^^^^^
              > 37 |                   exit 1
              | ^^^^^^^^^^^^^^^^^^^^^^^^^
              > 38 |                 fi
              | ^^^^^^^^^^^^^^^^^^^^^^^^^
              > 39 |                 echo ""
              | ^^^^^^^^^^^^^^^^^^^^^^^^^
              > 40 |                 echo "All validations passed!"
